# Generated by Django 4.2.7 on 2023-11-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cevent',
            options={'ordering': ('date',), 'verbose_name_plural': 'CEvents'},
        ),
    ]
